set(headers ${headers}
	src/PCH.h
    src/log.h
    src/settings.h
    src/InputManager.h
    src/MenuChecker.h
    src/MatchmakerMenuManager.h
    src/api/ThreeDUIInterface001.h
    src/api/ThreeDUIActorMenu.h
    src/config/ConfigStorage.h
    src/config/ConfigStoragePapyrusAdapter.h
    src/config/ConfigOptions.h
    src/ostim/OstimScene.h
    src/ostim/OstimStandaloneSceneLoader.h
    src/ostim/OstimTranslationLoader.h
    src/ostim/OstimThreadInterface.h
    src/ostim/ThreadTracker.h
    src/ostim/OstimPapyrusAPI.h
    src/ostim/OstimThreadBuilderInterface.h
    src/ostim/CompatibilityTable.h
    src/persistence/FormKeyUtil.h
    src/persistence/ThreadStorageManager.h
    src/persistence/SaveGameDataManager.h
    src/menu/NearbyActorFinder.h
    src/menu/SceneStartManager.h
    src/menu/UIExtActorSelector.h
    src/menu/ThreadMenu.h
    src/menu/ActorActivationHandler.h
    src/menu/ThreadMenuHotkeyManager.h
    src/menu/SexlabThreadMenu.h
    src/papyrus/PapyrusInterface.h
    src/papyrus/PapyrusMatchmakerVRApi.h
    src/sexlab/SexlabSceneTracker.h
    src/sexlab/SexlabSceneLoader.h
    src/sexlab/SexlabPapyrusInterface.h
    src/sexlab/SexlabPapyrusAPI.h
    src/sexlab/SexlabCreatureRaceMapper.h
    src/sexlab/CategoryRepository.h
    src/sexlab/SexlabCategoryFilter.h
    src/sexlab/SexlabIconResolver.h
    src/sexlab/SexlabSceneFilter.h
    src/sexlab/SexlabSceneStartManager.h
    external/VRManagerAPI.h
    external/PapyrusVRTypes.h
    external/VRHookAPI.h
    external/PapyrusVRAPI.h
    external/OpenVRTypes.h
)
