set(headers ${headers}
	src/PCH.h
    src/log.h
    src/settings.h
    src/InputManager.h
    src/MenuChecker.h
    src/VRSexMenuManager.h
    src/api/ThreeDUIInterface001.h
    src/api/ThreeDUIActorMenu.h
    src/config/ConfigStorage.h
    src/config/ConfigStoragePapyrusAdapter.h
    src/config/ConfigOptions.h
    src/ostim/OstimScene.h
    src/ostim/OstimStandaloneSceneLoader.h
    src/ostim/OstimTranslationLoader.h
    src/ostim/OstimThreadInterface.h
    src/ostim/OstimVRApi.h
    src/ostim/OstimVRPluginAPI.h
    src/ostim/ThreadTracker.h
    src/ostim/OstimPapyrusAPI.h
    src/ostim/OstimThreadBuilderInterface.h
    src/ostim/CompatibilityTable.h
    src/ostim/ActorPropertyTable.h
    src/ostim/SceneTokens.h
    src/ostim/ThreadHeadIndex.h
    src/category/SceneCategory.h
    src/category/CategoryRepository.h
    src/category/CategorySceneIndex.h
    src/persistence/FormKeyUtil.h
    src/persistence/ThreadStorageManager.h
    src/persistence/SaveGameDataManager.h
    src/persistence/MenuViewState.h
    src/menu/NearbyActorFinder.h
    src/menu/SceneStartManager.h
    src/menu/UIExtActorSelector.h
    src/menu/ThreadMenu.h
    src/menu/ActorActivationHandler.h
    src/menu/ThreadMenuHotkeyManager.h
    src/papyrus/PapyrusInterface.h
    src/papyrus/PapyrusVRSexMenuApi.h
    external/VRManagerAPI.h
    external/PapyrusVRTypes.h
    external/VRHookAPI.h
    external/PapyrusVRAPI.h
    external/OpenVRTypes.h
)
