set(sources ${sources}
    src/plugin.cpp
    src/InputManager.cpp
    src/MenuChecker.cpp
    src/MatchmakerMenuManager.cpp
    src/api/ThreeDUIInterface001.cpp
    src/config/ConfigStorage.cpp
    src/config/ConfigOptions.cpp
    src/ostim/OstimStandaloneSceneLoader.cpp
    src/ostim/OstimTranslationLoader.cpp
    src/ostim/OstimPapyrusAPI.cpp
    src/ostim/OstimThreadBuilderInterface.cpp
    src/ostim/OstimThreadInterface.cpp
    src/ostim/ThreadTracker.cpp
    src/ostim/CompatibilityTable.cpp
    src/ostim/PaginationFlattener.cpp
    src/persistence/FormKeyUtil.cpp
    src/persistence/ThreadStorageManager.cpp
    src/persistence/SaveGameDataManager.cpp
    src/menu/NearbyActorFinder.cpp
    src/menu/SceneStartManager.cpp
    src/menu/UIExtActorSelector.cpp
    src/menu/ThreadMenu.cpp
    src/menu/ActorActivationHandler.cpp
    src/menu/ThreadMenuHotkeyManager.cpp
    src/menu/SexlabThreadMenu.cpp
    src/util/MessageBoxUtil.cpp
    src/papyrus/PapyrusInterface.cpp
    src/sexlab/SexlabSceneTracker.cpp
    src/sexlab/SexlabSceneLoader.cpp
    src/sexlab/SexlabPapyrusInterface.cpp
    src/sexlab/SexlabPapyrusAPI.cpp
    src/sexlab/SexlabCreatureRaceMapper.cpp
    src/sexlab/CategoryRepository.cpp
    src/sexlab/SexlabCategoryFilter.cpp
    src/sexlab/SexlabIconResolver.cpp
    src/sexlab/SexlabSceneFilter.cpp
    src/sexlab/SexlabSceneStartManager.cpp
    external/PapyrusVRTypes.cpp
)
