set(sources ${sources}
    src/plugin.cpp
    src/InputManager.cpp
    src/MenuChecker.cpp
    src/VRSexMenuManager.cpp
    src/api/ThreeDUIInterface001.cpp
    src/config/ConfigStorage.cpp
    src/config/ConfigOptions.cpp
    src/ostim/OstimStandaloneSceneLoader.cpp
    src/ostim/OstimTranslationLoader.cpp
    src/ostim/OstimPapyrusAPI.cpp
    src/ostim/OstimThreadBuilderInterface.cpp
    src/ostim/OstimThreadInterface.cpp
    src/ostim/ThreadTracker.cpp
    src/ostim/CompatibilityTable.cpp
    src/ostim/PaginationFlattener.cpp
    src/persistence/FormKeyUtil.cpp
    src/persistence/ThreadStorageManager.cpp
    src/persistence/SaveGameDataManager.cpp
    src/menu/NearbyActorFinder.cpp
    src/menu/SceneStartManager.cpp
    src/menu/UIExtActorSelector.cpp
    src/menu/ThreadMenu.cpp
    src/menu/ActorActivationHandler.cpp
    src/menu/ThreadMenuHotkeyManager.cpp
    src/util/MessageBoxUtil.cpp
    src/papyrus/PapyrusInterface.cpp
    external/PapyrusVRTypes.cpp
)
